// solid/src/Anchor.tsx
import { type ParentComponent } from 'solid-js'
import { addHash } from '../../lib/util'
import { getHash } from './state'

export const Anchor: ParentComponent<{ onClick: () => void }> = props => (
  <a
    href={addHash(getHash())}
    onClick={(e: Event) => {
      e.preventDefault()
      props.onClick()
    }}
  >
    {props.children}
  </a>
)

// preact/src/Anchor.tsx
import { useCallback } from 'preact/hooks'
import { addHash } from '../../lib/util'
import { useNotice, state } from './state'

export const Anchor: preact.FunctionComponent<{
  onClick: () => void
}> = ({ onClick, children }) => {
  const hash = useNotice(state.hash)
  const onClickHandler = useCallback(
    (e: Event) => {
      e.preventDefault()
      onClick()
    },
    [onClick]
  )
  return (
    <a href={addHash(hash)} onClick={onClickHandler}>
      {children}
    </a>
  )
}
