// preact/src/App.tsx
import { useEffect } from 'preact/hooks'
import { Droppable } from './Droppable'
import { fail, state, useNotice } from './state'
import { Menu, about } from './Menu'
import { Results } from './Results'
import { NewKey } from './NewKey'
import { PrivateKeyView } from './PrivateKeyView'
import { PublicKeyView } from './PublicKeyView'

const Main: preact.FunctionComponent<{
  children?: never
}> = () => {
  const mode = useNotice(state.mode)
  if (mode === '#.') return <NewKey />
  if (mode != null) return <PrivateKeyView privateKey={mode} key={mode} />
  return <PublicKeyView />
}

const Top: preact.FunctionComponent<{ children?: never }> = () => {
  const openFile = useNotice(state.openFile)
  return (
    <Droppable className="openpgp-app" onDrop={openFile}>
      <div className="openpgp-left-column">
        <Menu onFileOpen={openFile} />
        <div className="openpgp-main">
          <Main />
        </div>
      </div>
      <Results className="openpgp-result-list" />
    </Droppable>
  )
}

const onHashChange = (): void => {
  state.processHash(window.location.hash).catch(fail)
}

export const App: preact.FunctionComponent<{ children?: never }> = () => {
  useEffect(() => {
    window.addEventListener('hashchange', onHashChange)
    return () => {
      window.removeEventListener('hashchange', onHashChange)
    }
  }, [])
  useEffect(() => {
    onHashChange()
    about()
  }, [])
  return <Top />
}

// solid/src/App.tsx
import type { VoidComponent, JSX } from 'solid-js'
import { isServer } from 'solid-js/web'
import { onCleanup, onMount } from 'solid-js'
import { getMode, getOpenFile, state } from './state'
import { Droppable } from './Droppable'
import { Results } from './Results'
import { Menu } from './Menu'
import { NewKey } from './NewKey'
import { PrivateKeyView } from './PrivateKeyView'
import { PublicKeyView } from './PublicKeyView'

const mainComponent = (): JSX.Element => {
  const mode = getMode()
  if (mode === '#.') return <NewKey />
  if (mode != null) return <PrivateKeyView privateKey={mode} />
  return <PublicKeyView />
}

const onHashChange = (): void => {
  state.processHash(window.location.hash).catch(state.fail.bind(state))
}

export const App: VoidComponent = () => {
  if (!isServer) {
    onMount(() => {
      window.addEventListener('hashchange', onHashChange)
    })
    onCleanup(() => {
      window.removeEventListener('hashchange', onHashChange)
    })
    onMount(onHashChange)
  }
  return (
    <Droppable class="openpgp-app" onDrop={getOpenFile()}>
      <div class="openpgp-left-column">
        <Menu />
        <div class="openpgp-main">{mainComponent()}</div>
      </div>
      <Results class="openpgp-result-list" />
    </Droppable>
  )
}
