// preact/src/UserID.tsx
import type { SingleKey } from '../../lib/key'

export const UserID: preact.FunctionComponent<{
  pgpKey: SingleKey
  children?: never
}> = ({ pgpKey: key }) => (
  <>
    {key.userName}
    {key.email != null && (
      <>
        {' '}
        <a className="openpgp-userid-email" href={`mailto:${key.email}`}>
          {key.email}
        </a>
      </>
    )}
  </>
)

// solid/src/UserID.tsx
import { type VoidComponent, Show } from 'solid-js'
import type { SingleKey } from '../../lib/key'

export const UserID: VoidComponent<{ key: SingleKey }> = props => (
  <>
    {props.key.userName}
    <Show when={props.key.email}>
      {email => (
        <>
          {' '}
          <a class="openpgp-userid-email" href={`mailto:${email()}`}>
            {email()}
          </a>
        </>
      )}
    </Show>
  </>
)
